# This file is added to cdk-addons from ./bundled-templates during the snap
# build. This secret is needed to run the cloud-controller-manager with
# cloud-provider-openstack. It was removed upstream when docs changed from
# 'kubectl apply <this.yaml>' to 'kubectl create secret' (commit a48fb753),
# yet applying this is simpler than automating secret creation in cdk-addons.
kind: Secret
apiVersion: v1
metadata:
  name: cloud-config
  namespace: kube-system
data:
  cloud.conf: {{ cloud_conf }}
{% if endpoint_ca_cert %}
  endpoint-ca.cert: {{ endpoint_ca_cert }}
{% endif %}
