apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cdk-cinder
  annotations:
    juju.io/workload-storage: "true"
provisioner: cinder.csi.openstack.org
{% if cinder_availability_zone %}
parameters:
  availability: "{{ cinder_availability_zone }}"
{% endif %}
