apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cdk-azure-disk
  annotations:
    juju.io/workload-storage: "true"
provisioner: kubernetes.io/azure-disk
parameters:
  storageaccounttype: Standard_LRS
  kind: managed
