#!/bin/sh
set -eu

app=$1

echo "Building $app v$KUBE_VERSION"

build_dir=build/$app
rm -rf $build_dir
mkdir -p $build_dir

sed "s/KUBE_VERSION/$KUBE_VERSION/g" $app.yaml > $build_dir/snapcraft.yaml

export KUBE_SNAP_ROOT=$(readlink -f .)
cd $build_dir
snapcraft
mv *.snap ..
