#!/bin/bash
set -eu

app="$1"
dest=$(readlink -f "$2")
set +u; KUBE_SNAP_BINS="$KUBE_SNAP_BINS"; set -u

if [ -z "$KUBE_SNAP_BINS" ]; then
  echo "KUBE_SNAP_BINS is not set, downloading $app from upstream"
  export KUBE_SNAP_BINS=$KUBE_SNAP_ROOT/build/kube_bins/$KUBE_VERSION
  mkdir -p $KUBE_SNAP_BINS
  pushd $KUBE_SNAP_BINS
  wget -N \
    https://storage.googleapis.com/kubernetes-release/release/v${KUBE_VERSION}/bin/linux/amd64/$app
  chmod +x $app
  popd
fi

cp "$KUBE_SNAP_BINS/$app" "$dest"
